const $=id=>document.getElementById(id); if($('year')) $('year').textContent=new Date().getFullYear();
const modelSources = [
  {name:'Thingiverse', formats:'STL, OBJ, 3MF, ZIP', license:'Creative Commons varies per model. Check before commercial use.', best:'huge maker library, functional parts, toys, brackets, upgrades', url:'https://www.thingiverse.com/'},
  {name:'Printables', formats:'STL, 3MF, OBJ, G-code, AMF', license:'varies per model; some reseller/commercial options', best:'practical prints, printer upgrades, contests, verified makes', url:'https://www.printables.com/'},
  {name:'MakerWorld', formats:'3MF, STL', license:'varies; check model page', best:'3MF print profiles, Bambu-style project files, popular consumer prints', url:'https://makerworld.com/'},
  {name:'Thangs', formats:'STL, 3MF, OBJ and marketplace files', license:'varies; includes free, paid, subscription and commercial tags', best:'3D model search, geometric search, popular printable designs', url:'https://thangs.com/'},
  {name:'MyMiniFactory', formats:'STL and other printable formats', license:'free and paid; designer license varies', best:'guaranteed printable models, tabletop, toys, props', url:'https://www.myminifactory.com/'},
  {name:'Cults3D', formats:'STL, OBJ, 3MF, CAD', license:'free and paid; commercial rights vary', best:'premium printable designs, toys, décor, cosplay', url:'https://cults3d.com/'},
  {name:'NIH 3D', formats:'STL and other open 3D formats', license:'Creative Commons or Public Domain, model dependent', best:'medical, anatomical, biology, education', url:'https://3d.nih.gov/'},
  {name:'NASA 3D Resources', formats:'STL, OBJ, BLEND and more', license:'NASA usage guidelines; many assets free to use', best:'spacecraft, satellites, planets, mission models', url:'https://science.nasa.gov/3d-resources/'},
  {name:'Smithsonian 3D', formats:'OBJ, glTF and downloadable 3D scans', license:'Open Access / CC0 where marked', best:'museum objects, fossils, culture, history, education', url:'https://3d.si.edu/'},
  {name:'Scan the World', formats:'STL/OBJ through MyMiniFactory listings', license:'Creative Commons varies by object', best:'cultural artefacts, statues, scanned objects', url:'https://www.myminifactory.com/scantheworld/'},
  {name:'Sketchfab downloadable', formats:'OBJ, glTF, FBX, STL sometimes', license:'Creative Commons varies; filter by downloadable and license', best:'3D previews, scans, visual models needing print cleanup', url:'https://sketchfab.com/3d-models?features=downloadable'},
  {name:'Yeggi', formats:'search engine for STL/OBJ/3MF', license:'depends on source site', best:'finding printable models across many repositories', url:'https://www.yeggi.com/'},
  {name:'STLFinder', formats:'search engine for STL files', license:'depends on source site', best:'fast STL search across the web', url:'https://www.stlfinder.com/'},
  {name:'GrabCAD Library', formats:'STEP, STL, OBJ, CAD formats', license:'varies; not all models are print-ready', best:'engineering parts, CAD references, prototypes', url:'https://grabcad.com/library'},
  {name:'Free3D', formats:'OBJ, STL, FBX and others', license:'free and paid; check license', best:'general 3D assets, some printable after cleanup', url:'https://free3d.com/'},
  {name:'CGTrader free models', formats:'OBJ, STL and many 3D formats', license:'free and paid; commercial terms vary', best:'professional assets and printable models', url:'https://www.cgtrader.com/free-3d-models'},
  {name:'Pinshape', formats:'STL and printable files', license:'varies', best:'maker projects and hobby prints', url:'https://pinshape.com/'},
  {name:'YouMagine', formats:'STL and open-source print files', license:'varies, often open licences', best:'older open-source 3D printing community models', url:'https://www.youmagine.com/'}
];
$('generate')?.addEventListener('click',()=>{const prompt=$('prompt').value.trim()||'A custom printable object';const style=$('style').value;const file=$('file').files[0];$('brief').textContent=`SHAPEFORGE 3D PROJECT BRIEF\n\nPROJECT TYPE: ${style}\n\nCUSTOMER PROMPT:\n${prompt}\n\nDELIVERY OPTIONS:\n• Print at home: provide STL / 3MF / OBJ download pack\n• ShapeForge prints it: quote material, colour, quality, quantity and delivery\n\nPRINTABILITY CHECKLIST:\n• Watertight mesh\n• Correct scale and units\n• Wall thickness 1.2mm+ for PLA/PETG\n• Flat print base where possible\n• Support and overhang review\n• Tolerance check for moving or fitted parts\n\nREFERENCE FILE:\n${file?file.name:'No file uploaded yet'}\n\nNEXT BACKEND STEP:\nConnect this workflow to AI model generation, mesh repair, storage, payment and order management APIs.`; if(file&&file.type.startsWith('image/')){const r=new FileReader();r.onload=e=>$('preview').innerHTML=`<img src="${e.target.result}" alt="Uploaded reference preview">`;r.readAsDataURL(file)}else{$('preview').innerHTML=''}});
$('quoteForm')?.addEventListener('submit',e=>{e.preventDefault();const grams=+$('grams').value||0,qty=+$('qty').value||1,rate=+$('material').value,finish=+$('finish').value||0;const setup=22;const price=(setup+(grams*rate)+finish)*qty;$('quoteResult').textContent=`Estimated ShapeForge print price: $${price.toFixed(2)} AUD. Final price depends on model complexity, supports, finishing, packing and delivery.`;});
let scanStream=null;const cameraPreview=$('cameraPreview');$('startScan')?.addEventListener('click',async()=>{try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});cameraPreview.srcObject=scanStream;await cameraPreview.play();}catch(err){$('scanBrief').textContent='Camera could not open. Upload the site to HTTPS/Netlify, open on a phone, and allow camera permission. You can still upload photos in the AI Studio.';}});$('stopScan')?.addEventListener('click',()=>{if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null;cameraPreview.srcObject=null;}});$('scanBriefBtn')?.addEventListener('click',()=>{const notes=$('scanNotes').value.trim()||'Customer wants a real object scanned and converted into a printable 3D model.';$('scanBrief').textContent=`MOBILE SCAN BRIEF\n\nCUSTOMER NOTES:\n${notes}\n\nCAPTURE GUIDE:\n• Take 20 to 60 photos around the object\n• Keep lighting even and avoid shiny glare\n• Include front, back, sides, top and detail shots\n• Add a ruler or coin for scale\n• Use plain background where possible\n\nPRODUCTION WORKFLOW:\n1. Build photogrammetry / LiDAR / CAD reference\n2. Clean mesh and make it watertight\n3. Check scale, wall thickness and tolerances\n4. Export STL/3MF for slicing\n5. Customer chooses download or ShapeForge print service`;});
document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.mode; $('printPlan').textContent = mode==='home' ? `PRINT AT HOME PACK\n\nCustomer receives:\n• STL for universal slicing\n• 3MF for colour/material/project data where available\n• OBJ for editable 3D workflows\n• Printer setup notes\n• Slicer checklist\n• Licence and usage notes\n\nFuture live feature:\nDirect send to supported printer/cloud services after account linking.` : `SHAPEFORGE PRINT-FOR-ME ORDER\n\nCustomer chooses:\n• Material: PLA, PETG, resin, nylon or carbon fibre nylon\n• Colour and surface finish\n• Layer height / quality\n• Infill and strength\n• Quantity\n• Standard or express shipping\n\nAdmin receives:\n• Printable file / scan brief\n• Quote details\n• Production queue status\n• Customer contact and delivery notes`; }));
let deferredInstallPrompt=null;const installButtons=[$('installApp'),$('installHero')].filter(Boolean);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;});installButtons.forEach(btn=>btn.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;}else{alert('To install: open this site on your phone, tap browser menu, then choose Add to Home screen / Install app. Camera scanning works after upload to HTTPS.');}}));if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));}
function renderLibrary(){const box=$('libraryResults'); if(!box)return;const q=($('librarySearch')?.value||'').toLowerCase();const filter=($('libraryFilter')?.value||'all').toLowerCase();const filtered=modelSources.filter(s=>{const text=(s.name+' '+s.formats+' '+s.license+' '+s.best).toLowerCase();return(!q||text.includes(q))&&(filter==='all'||text.includes(filter));});box.innerHTML=filtered.map(s=>`<article><b>${s.name}</b><p><strong>Formats:</strong> ${s.formats}</p><p><strong>Best for:</strong> ${s.best}</p><p><strong>Licence:</strong> ${s.license}</p><a class="btn small" href="${s.url}" target="_blank" rel="noopener">Open source</a></article>`).join('')||'<article><b>No match</b><p>Try STL, OBJ, 3MF, NASA, medical, tools, public domain or Creative Commons.</p></article>';}
['librarySearch','libraryFilter'].forEach(id=>$(id)?.addEventListener('input',renderLibrary));renderLibrary();